# Generated by Django 5.1.4 on 2025-01-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fotografia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("legenda", models.CharField(max_length=150)),
                ("descricao", models.TextField(max_length=150)),
                ("foto", models.CharField(max_length=100)),
            ],
        ),
    ]
