# Generated by Django 5.1.4 on 2025-01-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0002_fotografia_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="foto",
            field=models.CharField(max_length=150),
        ),
    ]
