# Generated by Django 5.1.4 on 2025-01-30 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0003_fotografia_publicada_alter_fotografia_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="data_fotografia",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
