# Generated by Django 5.1.4 on 2025-04-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0006_fotografia_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=True),
        ),
    ]
